---
title: "Dissertation"
output: html_document
---


<style>
  .column-left{
    float: left;
    width: 70%;
    text-align: left;
  }
  
  .column-right{
    float: right;
    width: 25%;
    text-align: left;
  }
</style>


<div class="column-left">

The practice of politics is  inherently social. The relationships between political participants form networks which encourage and constrain political activity. Yet social and political divisions are growing among American partisans, with Republicans and Democrats finding it difficult to perform a basic function of democratic politics: talking to individuals across the political divide. An important mechanism of growing political polarization in the electorate involves citizens' social networks. Individuals lean on others when forming opinions - what teams to like, what foods to try, and even which politicians to support. The reality that individuals are increasingly surrounded by others who are similar to themselves along demographic and partisan lines is potentially quite consequential for the social component of attitude formation. This dissertation seeks to shed new light on social explanations of political activity by accounting for the reasons individuals select into or out of groups and how the group then impacts their political decisions and attitudes. To address these topics, I utilize data from the 2000 ANES, 2008 ANES Panel Study, and new data from the 2016 CCES. Both surveys ask respondents a battery of questions about the people with whom they most frequently discuss politics, including perceived vote choice and level of political knowledge. Using these data, I offer an updated analysis of how polarization is influencing---and is influenced by---social network homogeneity.
	
This dissertation extends previous work on the relationship between American voters' political discussion networks and political activity into a time of increased polarization. The work will focus on questions related to the development and impacts of individuals' core social networks. First, are these core networks homogeneous today and how have they changed in recent years? Second, how does group composition impact perceptions of individuals on the other side of the aisle? Third, to the extent that politically homogeneous networks exist, who rejects divergent views and why? Finally, what mechanisms distort perceptions of in- and out-group members?

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-125325302-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-125325302-1');
</script>

</div>



<div class="column-right">
**Ross Butters** <br />
Department of Political Science <br />
University of California, Davis <br />
One Shields Avenue <br />
Davis, CA 95816 <br />
rbutters@ucdavis.edu 
</div>