---
title: ""
output: html_document
---

[//]: (!!!some sort of note)

[//]: (Theme options in _site.yml include: default, cerulean, journal, flatly, readable, spacelab, united, cosmo, lumen, paper, sandstone, simplex, and yeti --- I like cerulean, spacelab, cosmo, lumen, and paper)


<style>
  .column-left{
    float: left;
    width: 70%;
    text-align: left;
  }
  
  .column-right{
    float: right;
    width: 25%;
    text-align: left;
  }
</style>

<br>



<div style= "float:right;position: relative; top: -80px;">
```
IMG_7002-2-rbutters-Ross_Butters-rbutters@ucdavis.edu.jpg
```
</div>

<div class="column-left">
I am a PhD candidate in the Department of Political Science at the University of California, Davis. My research focuses on the impact of social factors on individual political attitudes and behavior. Specifically, I am interested in understanding how composition of political communication networks, and the information therein, influences political attitudes and participation of individuals. I also examine what contextual factors influence the composition of these networks. Prior to graduate school, I
</div>

<div class="column-right">
**Ross Butters** <br />
Department of Political Science <br />
University of California, Davis <br />
One Shields Avenue <br />
Davis, CA 95816 <br />
rbutters@ucdavis.edu 
</div>

