---
title: ""
output: html_document
---

<style>
  .column-left{
    float: left;
    width: 30%;
    text-align: left;
  }
  .column-center{
    display: inline-block;
    width: 47%;
    text-align: left;
  }
  .column-right{
    float: right;
    width: 23%;
    text-align: left;
  }
</style>

<div class="column-left">

### **Teaching Interests:**

American Politics

Political Behavior 

Social Networks and Influence 

Survey and Research Design

Political and Policy Analysis in California
</div>


<div class="column-center">
### **Teaching Experience:**

#### *Adjunct Assistant Professor*

[Policy Analysis in California, June 2020-Aug. 2020, June 2021-Present](Pol 195 Syllabus.pdf)

[Advocacy for Policy Change in California, June 2020-Present](Pol 193 Syllabus.pdf)

Seminar in American Politics, Aug. 2020-Present

[Research Methods for Political Science and Public Policy, Aug. 2020-June 2021](Pol 196E Syllabus.pdf)



#### *Associate Instructor*

[Introduction to American Politics, Sept. 2017-Dec. 2017](Pol_1_Syllabus_2017F.pdf)

#### *Teaching Assistant*

Research Methods in Politics and Policy, Jan. 2018-June 2020

Policy Analysis in California, Jan. 2018-June 2020, June 2017-August 2017 

Mass Media and Politics, March 2016-June 2016

Introduction to Comparative Politics, Jan. 2016-March 2016

American Government: The Presidency, April 2015-June 2015

West European Politics: German Politics Jan. 2015-March 2015

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-125325302-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-125325302-1');
</script>

</div>

<div class="column-right">
<br>
**Ross Butters** <br />
University of California Center Sacramento <br />
1130 K Street, Suite LL22 <br />
Sacramento, CA 95814 <br />
rbutters@ucdavis.edu 
</div>

