---
title: "Working Papers"
output: html_document
---

<style>
  .column-left{
    float: left;
    width: 70%;
    text-align: left;
  }
  
  .column-right{
    float: right;
    width: 25%;
    text-align: left;
  }
</style>

<div class="column-left">

**Polarized Networks? New Evidence on American Voters' Political Discussion Networks**

with Christopher Hare, University of California, Davis

An important mechanism of mass political polarization involves citizens' social networks: how politically homogeneous are they, how has this changed over recent years, and which individual and contextual variables predict the degree of homogeneity in social networks? Moreover, what are the consequences of network homogeneity on political preferences and in and out-group perceptions? In this paper, we address these questions by combining data from the 2000 American National Election Study and new data from the 2016 Cooperative Congressional Election Study. Both surveys ask respondents a battery of questions about the people with whom they most frequently discuss politics, including perceived vote choice and level of political knowledge. Using these data, we offer an updated empirical assessment of how polarization is influencing---and is influenced by---social network homogeneity.


**Revisiting Social Networks and Correct Voting**

with Anand Sokhey, University of Colorado, Boulder

While the role of social influence in public opinion and political behavior is well-established, the question of how exposure to interpersonal disagreement affects the *quality* of democratic decision-making has received less attention. Following Lau and Redlawsk's (e.g., 1997) approach to operationalizing such activity, we build on research examining whether our social networks help us make "good" decisions. Previous work found a link between disagreeable networks and lower rates of correct voting in older data sets; we examine whether this relationship obtains in more recent electoral contexts and is robust to different ways of thinking about interpersonal disagreement. Looking at all presidential elections since 2000, we find extremely consistent results that support the original conclusions: exposure to interpersonal disagreement predicts lower rates of correct voting. We close by reflecting on these findings, and discuss the evidence for different mechanisms of influence. 


**The Secret to Senate Holds: Historical Analysis and Quantification of the Impact of Holds**

with Janet M. Box-Steffensmeier, The Ohio State University, and Alison Craig, University of Texas, Austin

There are many forms of obstruction in the United States Senate, but some are less public than others.  A Senate Hold is an effective and critical component of the modern Congress.  A senator can place an anonymous hold on any piece of legislation or nomination before the Senate by informing their party leader.  A hold will stop or kill a bill or nomination and may be used to leverage concessions.  This project examines the procedural innovation of the hold by Lyndon B. Johnson in the 1950s.  Our research has uncovered the earliest available data on the use of Senate holds from the archive of Senate leader Lyndon Johnson, which is in contrast to the conventional wisdom, which states that holds began much later in the 1970s.  The record and logic shows that holds developed under Johnson as a way to manage legislation being passed under unanimous consent agreements.  We provide insightful historical information about the development of Senate holds and compare the usage and impact of holds.  The use of holds for the operation of the Senate is important for examining questions of fairness, efficiency and majority/minority rights. 


**The Influence of Partisan Polarization and Geographic Neighborhood Context on Congressional Cosponsorship Policy Networks**

with Carlos Algara, University of California, Davis

The classical “Textbook Theory” of Congress posits that legislators are relatively autonomous actors who work together on a bipartisan basis to maximize their probability of re-election (Shepsle 1989). This classical district-centered theory of Congress posits that legislators are motivated to engage in bipartisan legislative behavior and work together by the geographical similarity of their respective districts. Congressional scholars have largely cast doubt on the importance of district-centered considerations to inform the behavior of legislators, shifting the focus to partisan-centered preferences (Rohde 1991, Cox & McCubbins 1993, 2005). Moreover, while scholars have debated these theories, they have said relatively little about the salience of these theories across varying policy issues. Using the distinct expression of legislative behavior provide by bill co-sponsorship and geographic proximity methods we explore the extent to which district similarity influences how legislators work together in the Congressional network across varying degrees of partisan polarization. Treating Congress as a series of distinct policy networks and using exponential random graph models (ERGM), we evaluate a theory arguing that geographic proximity is a salient predictor of legislator cooperation in district-centered policy domains (i.e. agriculture, land management), even during the hyper-partisan contemporary.

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-125325302-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-125325302-1');
</script>

</div>


<div class="column-right">
**Ross Butters** <br />
University of California Center Sacramento <br />
1130 K Street, Suite LL22 <br />
Sacramento, CA 95814 <br />
rbutters@ucdavis.edu 
</div>


